### ISSUE TITLE
Any plan to create a compatible thermal api for wordpress?

### ISSUE THREAD

**Issue by steve21124** [tweichart/JSON-API-for-BuddyPress#6]
recently, there is thermal api for wordpress. It is rest and json and might be the next standard api for wordpress. Any plan to make json-api compatible with that?

**Comment by tweichart** [comment]
I don't have any plans on this, I'm still connecting to the JSON API for Wordpress and as long as I'm not having any problems with that or any disadvantages by using this plugin I think I'll stick to it ;-)
