### ISSUE TITLE
Member Avatar

### ISSUE THREAD

**Issue by aheadzen** [tweichart/JSON-API-for-BuddyPress#7]
Great plugin. Helped me.

I needed member avatar and couldn't figure out anything so hacked plugin to add this code to profile_get_profile function.

$oReturn->avatar->thumb = apply_filters( 'bp_get_displayed_user_avatar', bp_core_fetch_avatar( array( 'item_id' => $oUser->data->ID, 'type' => 'thumb', 'html' => false ) ) );
$oReturn->avatar->full = apply_filters( 'bp_get_displayed_user_avatar', bp_core_fetch_avatar( array( 'item_id' => $oUser->data->ID, 'type' => 'full', 'html' => false ) ) );
$oReturn->meta = get_userdata($oUser->data->ID);

Would appreciate if you could add this feature in plugin itself so my changes aren't lost with next update to this plugin.

Thanks

**Comment by tweichart** [comment]
Hey there,

great you like the plugin. I've added your code with the single addition,
that I look for the list_users permission before I add the information.
I've put up rel. 1.0.2, if you want some credit for the code just tell me
and I'll add it ;-)

Greetings Toby

2014-02-02 aheadzen notifications@github.com:
